# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 850d6fee502dc3c7af750d979f579602bbb55b51cae09847dcbd850efabc6f1491eda8fbca9508a415e8db3c4dd0b0b0e0c51ab79aaee6e346b492841a0721a1

test:
  secret_key_base: 2d24a75742081bdab01f27cd7e53ac802594e998b58648a11b026e1ae98b0335c862b99148d6a7f0f83c5c3805c6ceb0669eda0c5128bdb3454c5c7857011896

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
